name: CI (BE Build, Test, Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pmm_be
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make gradlew executable (Linux)
        run: chmod +x ./gradlew

      - name: Build & Test (Gradle)
        run: ./gradlew clean test

      - name: Upload Test Report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: pmm_br/build/reports/tests/test/   # <<< ชี้ path ให้ตรง

  docker:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: vars
        run: |
          SHA=${GITHUB_SHA::7}
          echo "latest=${{ secrets.DOCKERHUB_USERNAME }}/pmm_be:latest" >> $GITHUB_OUTPUT
          echo "sha=${{ secrets.DOCKERHUB_USERNAME }}/pmm_be:${SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker
        uses: docker/build-push-action@v6
        with:
          context: ./pmm_br    # <<< Dockerfile อยู่ใน pmm_br
          push: true
          tags: |
            ${{ steps.vars.outputs.latest }}
            ${{ steps.vars.outputs.sha }}
